### ISSUE TITLE
Tagging semantics for latest

### ISSUE THREAD

**Issue by volschin** [H2CK/webtrees#11]
It is common use, that the latest tag contains the multiarch images from the latest released version. At the moment under latest only is an amd64 architecture image that has not the same hash as the amd64 image from the v2.0.2-0.
If you want an image from the lastest source you should call it master.

**Comment by H2CK** [comment]
You are correct. This error was introduced when switching to Travis CI for multi-arch support.
Fix should be introduced by #12

**Comment by H2CK** [comment]
Solved with version v2.0.2-1
