### ISSUE TITLE
Internal webtrees directories are exposed

### ISSUE THREAD

**Issue by kgawda** [H2CK/webtrees#17]
Some directories that are not expected to be published are available via browser.

Steps to reproduce:
  1. Prepare a database container called "mysql"
  1. Launch container `docker run -d -p 8443:443 --name webtrees --link mysql:db dtjs48jkt/webtrees:v2.0.5-1`
  1. Open https://localhost:8443 in browser, set up: database details, user and example tree
  1. Open https://localhost:8443/data/config.ini.php. A semicolon is displayed.

According to [Webtrees github](https://github.com/fisharebest/webtrees#security):
> In the unlikely event you do fetch the file (you will just see a semicolon), then that protection is not working on your site and you should take some further action.

**Comment by H2CK** [comment]
This should be fixed with PR #18 
The release version will be v2.0.5-2.

**Comment by H2CK** [comment]
Docker Image v2.0.5-2 is available on docker hub.
Thank you for your contribution.
