### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fisharebest** [H2CK/webtrees#22]
> Therefor you should create two directories that are mapped to the container internal directories /var/www/html/data and /var/www/html/media.

This was true for webtrees 1.x

Since webtrees 2.x, the media folder is *inside* the data folder.  So only the data folder is needed.

**Comment by H2CK** [comment]
The documentation will be fixed by the pull request #23 resulting in version v2.0.7-1.

**Comment by H2CK** [comment]
Release v2.0.7-1 was published.

**Comment by kotliary** [comment]
The /var/www/html/media folder is still in the Parameters section of README.md.

**Comment by H2CK** [comment]
Sorry. I did miss this one. I will fix it soon.
