### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by xXZaretXx** [H2CK/webtrees#25]
hello
today i tried to run this docker container..
i want to open the site and .. nothing happend..

i end up with the knowledge that some files + packages are missing
the files the container missed:
- 06_initialize_db.sh
- webtrees.sql
- config.ini.php
- the command "mysql" ist missing, too .. so it's needed to install mysql-client perhaps..

i think there is a lack of other files but i don't know

**Comment by H2CK** [comment]
Hi,
you are totally right. This affects the functionality for auto setting up the MySQL/MariaDB.
There are some settings lost when migrating to the Travis Build Pipeline.
I try to fix it as soon as possible.

**Comment by H2CK** [comment]
Fixed with version v2.0.9-1. Will be available on Docker Hub in a view minutes.
