### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by drojh** [H2CK/webtrees#30]
Hello

I keep getting this error when opening the site:

`RuntimeException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/html/app/Http/Middleware/UseDatabase.php:114 Stack trace: #0 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #1 /var/www/html/app/Http/Middleware/BadBotBlocker.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #2 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #3 /var/www/html/app/Http/Middleware/RegisterFactories.php(72): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #4 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #5 /var/www/html/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #6 /var/www/html/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #7 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #8 /var/www/html/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #9 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #10 /var/www/html/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #11 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #12 /var/www/html/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #13 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 /var/www/html/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 /var/www/html/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 /var/www/html/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 /var/www/html/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /var/www/html/index.php(57): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #22 {main}`

Using the following `docker-compose.yml`

```yml
version: '3.0'

services:
  webtrees:
    image: dtjs48jkt/webtrees
    restart: always
    ports:
      - 88:80
    environment:
      - DISABLE_SSL=TRUE
      - PORT=80
    volumes:
      - /webtrees/data:/var/www/html/data
      - /webtrees/media:/var/www/html/media
```

Shouldn't I see the DB setup config page?

**Comment by H2CK** [comment]
Hi.
I did try to start a fresh container and it was possible to successfully run the assistant. Even I have another instance successfully running with a PostgrSQL DB.
I assume your mounted volumes contain something that is not compatible with webtrees 2.x. With webtrees 2.x there us no need to mount a separate media volume any more (see #22). Are you still running webtrees 1.17.x? And your configuration data, plugin and so on in /webtrees/data is still based on webtrees 1.17.x? In this case you could use the tag dtjs48jkt/webtrees:v1.7.17 to make use of the old webtrees version.
Please have a look in your data folder and check if the content is compatible with webtrees 2.0.x

**Comment by H2CK** [comment]
It did some further analysis. It seems that your database settings might not be correct. Are you trying to connect to your DB (MySQL?) with localhost as hostname. Maybe try using 127.0.0.1.
SQLSTATE[HY000] [2002] No such file or directory means php cannot find the mysql.default_socket file. But this socket will not be available within this docker image, since the container does not contain a database.

**Comment by drojh** [comment]
Hey

Played around with it some more and got solved. Don't know what exactly went wrong, but as you mentioned, I think it was something to do with the mounted folders.
After changing them, it worked. (They were created by an earliere try.)
