### ISSUE TITLE
Upgrade PHP version?

### ISSUE THREAD

**Issue by nateswart** [H2CK/webtrees#31]
This docker image got me started very quickly, thank you!

Do you have any plans to update the PHP version?

![Screen Shot 2020-12-08 at 2 14 32 PM](https://user-images.githubusercontent.com/839888/101530449-f16c1200-395f-11eb-8db4-370f981794e0.png)

**Comment by H2CK** [comment]
I will try to release a new version based on php 7.4 soon.

**Comment by H2CK** [comment]
PHP 7.4 is introduced with version v2.0.10-1 and will be available on Docker Hub soon (After the build process finishes). See also #32.
