### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by 06Games** [H2CK/webtrees#37]
Hello, how to enable URL rewrite as shown [here](https://webtrees.net/faq/urls/) ?
I tried to map a `.htaccess` to `/var/www/html/.htaccess` but it looks like the rewrite mod is not enabled. 
How can I do it ? And would it be possible to add an option to do it automatically ?

**Comment by H2CK** [comment]
Hi, currently the pretty URLs are not supported. I will try to add this feature in the next release.
To answer your questions: Sure mod rewrite is available in the docker image, but .htaccess files are disabled for security reasons by the _AllowOverride None_ directive.

**Comment by H2CK** [comment]
Pretty Urls will be available with #38. This pull request will also integrate an update to Webtrees 2.0.11. Therefore Release v2.0.11-0 will contain the functionality.
Please have a look at the README for information how to enable pretty using  environment variables.
