### ISSUE TITLE
Add option to configure max uploaded file size via env variables

### ISSUE THREAD

**Issue by Speeedymauss** [H2CK/webtrees#55]
Hi,
it would be very practical if you could also determine the maximum upload size of the files via the Docker env variables.
This is set to 2M by default and is often too small for current files. Currently, this would have to be adjusted by changing the php.ini in the container.

**Comment by H2CK** [comment]
With the latest build for version 2.1.7 from 2022/09/13 (available soon on docker hub) you will be able to use `-e MAX_UPLOAD_SIZE` to set the maximum file upload size. The default will be 2M.

**Comment by Speeedymauss** [comment]
Unfortunately this fixed only one parameter. It is also needed to edit the post_max_size. This parameter is fixed to 8M and will limit the uploads to 8M even if the max_upload_size is higher.

**Comment by H2CK** [comment]
Functionality to set also post_max_size is added to the latest build for version 2.1.7 from 2022/09/16 (available soon on docker hub). Use `-e POST_MAX_SIZE` to set the maximum post size. The default will be 8M.
