### ISSUE TITLE
The Environment Variables introduced in #55 no longer seem to work

### ISSUE THREAD

**Issue by Tuetenk0pp** [H2CK/webtrees#60]
As the title says. Setting both `MAX_UPLOAD_SIZE `and `POST_MAX_SIZE `does no longer work.

![grafik](https://user-images.githubusercontent.com/55783419/206498677-6e4610cc-deca-434e-9fba-26ec5fa38cf2.png)

**Comment by H2CK** [comment]
Will be fixed in the latest updated image of version 2.0.12. (should be available in a few minutes on docker hub)
