### ISSUE TITLE
WT_ADMINPW not hashed properly on creation

### ISSUE THREAD

**Issue by esamson** [H2CK/webtrees#61]
When I set `WT_ADMINPW`, the created admin account gets a hashed password saved as `*0` in the database. So I can't log in with that account.

It's seems like an issue with a change in how PHP `crypt()` function works.

If I don't set `DB_PASSWORD` and just go through the manual set up, everything works as expected.

**Comment by H2CK** [comment]
You are totally right. The issue was cause by a change of the crypt method with php >8.
The creation of the password hash is corrected in the latest build of the image. Please pull the latest image from docker hub.
